#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

use File::Slurper qw(read_text);

binmode STDOUT, ":utf8";

my @w;

for my $file ("../devdata/French_proverbs") {
    my $ct = read_text $file;
    while ($ct =~ m!^<ul>\n^<li><i>(.+?)</i>!mgs) {
        push @w, $1;
    }
}

say for sort @w;
